[functions]
[functions.cancel-subscription]
verify_jwt = true

[functions.change-subscription]
verify_jwt = true

[functions.create-stripe-checkout]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.initialize-user]
verify_jwt = true
allowed_origins = ["http://localhost:5173", "http://localhost:3000", "https://poke-collector.netlify.app"]

[functions.stripe-webhook]
verify_jwt = true

[functions.test-stripe-config]
verify_jwt = true

[functions.send-email]
verify_jwt = false
allowed_origins = ["http://localhost:5173", "http://localhost:3000", "https://poke-collector.netlify.app"]

