[auth]
enabled = true
site_url = "https://poke-collector.netlify.app"
additional_redirect_urls = ["http://localhost:5173/", "https://poke-collector.netlify.app/"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[auth.mfa]
max_enrolled_factors = 10
[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true
[auth.mfa.phone]
enroll_enabled = false
verify_enabled = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
secure_password_change = false
max_frequency = "1m0s"
otp_length = 6
otp_expiry = 86400

[functions]
[functions.initialize-user]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.brevo-email-sender]
enabled = true
verify_jwt = true
import_map = "./functions/brevo-email-sender/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/brevo-email-sender/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/brevo-email-sender/*.html" ]
