### Test send-email function
POST http://localhost:54321/functions/v1/send-email
Content-Type: application/json
Authorization: Bearer v1,whsec_NLP7yuJ+3qdMrM77FgQ3N0LUr3drXnre2zhCn37X13JmISoB0PQ26IgbUhsm+7Qc9PBMLEz8fgsBZfkB

{
  "email": "test@example.com",
  "template": "confirmation",
  "data": {
    "confirmation_url": "https://pokecollector.com/confirm?token=123456",
    "html": "<h1>Test Email</h1><p>This is a test email.</p>",
    "preferred_lang": "es"
  }
}
